# This workflow will run tests on PRs

name: PyTest On PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Install dependencies and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run tests
        run: pytest tests --doctest-modules --cov=pybaseball --cov-report term-missing -n 5
      - name: Timing test
        timeout-minutes: 2
        run: python -m scripts.statcast_timing
      - name: Run MyPy
        run: mypy .
        continue-on-error: true
