# This workflow will run tests on PRs

name: PyTest On PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        python-version:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
    name: Install dependencies and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test TEST_FLAGS="-n 5"
      - name: Timing test
        timeout-minutes: 2
        run: python -m scripts.statcast_timing
      - name: Cache test
        run: make validate-cache
      - name: Run MyPy
        run: make mypy ONLY_MODIFIED=0
        continue-on-error: true
