from ..enum_base import EnumBase


class FangraphsTeams(EnumBase):
    ALL = '0'
    ARI = '15'
    ATL = '16'
    BAL = '2'
    BOS = '3'
    CHC = '17'
    CHW = '4'
    CIN = '5'
    CLE = '5'
    COL = '19'
    DET = '6'
    HOU = '21'
    KCR = '7'
    LAA = '1'
    LAD = '22'
    MIA = '20'
    MIL = '23'
    MIN = '8'
    NYM = '25'
    NYY = '9'
    OAK = '10'
    PHI = '26'
    PIT = '27'
    SDP = '29'
    SEA = '11'
    SFG = '30'
    STL = '28'
    TBR = '12'
    TEX = '13'
    TOR = '14'
    WSN = '24'
